[package]
name = "render"
version = "0.1.0"
authors = ["Oscar <oscar.shrimpton.personal@gmail.com>"]
edition = "2018"

[dependencies]
stockton-render = { path = "../../stockton-render" }
stockton-types = { path = "../../stockton-types" }
stockton-bsp = "2.0.0"
winit = "0.19.1"