[workspace]
members = [
    "stockton-types",
    "stockton-input",
    "stockton-input-codegen",
    "stockton-skeleton",
    "stockton-levels",
    "stockton-render",
    "stockton-contrib",
    "rendy-memory",
    "rendy-descriptor",
    "examples/render-quad",
    "examples/input-codegen",
]
