[workspace]
members = [
    "stockton-types",
    "stockton-render",
    "examples/render-triangles"
]


[patch.crates-io]
gfx-backend-gl = { git = "https://github.com/gfx-rs/gfx" }
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }