[package]
name = "stockton-render"
version = "0.1.0"
authors = ["Oscar <oscar.shrimpton.personal@gmail.com>"]
edition = "2018"

[dependencies]
stockton-types = { path = "../stockton-types" }
winit = "0.19.1"
gfx-hal = "0.2.0"
arrayvec = "0.4.10"

[features]
default = ["vulkan"]
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]
unstable = []

[dependencies.gfx-backend-gl]
version = "0.2"
features = ["glutin"]
optional = true

[dependencies.gfx-backend-vulkan]
version = "0.2"
optional = true

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies.gfx-backend-metal]
version = "0.2"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx11]
version = "0.2"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.2"
optional = true
