[package]
name = "stockton-render"
version = "0.1.0"
authors = ["Oscar <oscar.shrimpton.personal@gmail.com>"]

[dependencies]
stockton-types = { path = "../stockton-types" }
winit = "^0.21"
gfx-hal = "^0.5"
arrayvec = "0.4.10"
nalgebra-glm = "0.4.0"
shaderc = "0.6.1"
log = "0.4.0"

[features]
default = ["vulkan"]
vulkan = ["gfx-backend-vulkan"]

[dependencies.gfx-backend-vulkan]
version = "^0.5"
features = ["x11"]
optional = true
