[package]
name = "stockton-types"
version = "0.1.0"
authors = ["Oscar <oscar.shrimpton.personal@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18.0"
stockton-bsp = "1.0.0"
downcast-rs = "1.0.4"