[package]
name = "stockton-types"
version = "0.1.0"
authors = ["Oscar <oscar.shrimpton.personal@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra-glm = "^0.6"
stockton-bsp = "2.0.0"
downcast-rs = "1.0.4"