[package]
name = "stockton-input"
version = "0.1.0"
authors = ["Oscar Shrimpton <oscar.shrimpton.personal@gmail.com>"]
edition = "2018"

[dependencies]
stockton-skeleton = { path = "../stockton-skeleton" }
egui = "^0.2"
